/**
 * GenerationOriginPanel
 *
 * Shows the origin/source of a generation - how it was created.
 * Displays available metadata about AI generation vs manual/fallback.
 */

import {
  Sparkles,
  User,
  AlertTriangle,
  Cpu,
  RefreshCw,
} from 'lucide-react';
import { Badge } from '../ui';
import type { Generation } from '../../types';

interface GenerationOriginPanelProps {
  generation: Generation;
}

type GeneratedBy = 'ai' | 'manual' | 'fallback' | 'heuristic' | 'unknown';

// PROMPT 19: AI error stages
type AIErrorStage =
  | 'gateway_unreachable'
  | 'hooks_not_configured'
  | 'hooks_dispatch_failed'
  | 'no_response'
  | 'timeout'
  | 'empty_response'
  | 'invalid_shape'
  | 'validator_failed'
  | 'parse_failed'
  | 'provider_error'
  | 'unknown';

type AIErrorType = 'technical' | 'unusable_response' | 'none';

interface OriginMetadata {
  generated_by?: GeneratedBy;
  ai_attempted?: boolean;
  ai_succeeded?: boolean;
  fallback_used?: boolean;
  fallback_reason?: string;
  model?: string;
  /** PROMPT 16: Provider/gateway used for generation */
  provider?: string;
  /** PROMPT 16B: Runtime mode */
  runtime?: 'agent' | 'chat_completion';
  temperature?: number;
  tokens_used?: number;
  generation_time_ms?: number;
  // PROMPT 19: Detailed AI error fields
  ai_request_started?: boolean;
  ai_reached_gateway?: boolean;
  ai_raw_response_received?: boolean;
  ai_content_usable?: boolean;
  ai_error_type?: AIErrorType;
  ai_error_stage?: AIErrorStage;
  ai_error_code?: string;
  ai_error_message?: string;
}

// =============================================================================
// CONFIG
// =============================================================================

// PROMPT 14: Enhanced origin config with clearer labels
const originConfig: Record<GeneratedBy, {
  label: string;
  shortLabel: string;
  description: string;
  icon: React.ElementType;
  color: string;
  badgeVariant: 'success' | 'pending' | 'error' | 'inactive' | 'default';
}> = {
  ai: {
    label: 'Generated by AI',
    shortLabel: 'AI',
    description: 'Successfully created using AI model',
    icon: Sparkles,
    color: 'text-primary-400',
    badgeVariant: 'success',
  },
  manual: {
    label: 'Manual Creation',
    shortLabel: 'Manual',
    description: 'Created manually by a user',
    icon: User,
    color: 'text-blue-400',
    badgeVariant: 'default',
  },
  fallback: {
    label: 'Fallback Template',
    shortLabel: 'Fallback',
    description: 'AI generation failed - template used instead',
    icon: AlertTriangle,
    color: 'text-yellow-400',
    badgeVariant: 'pending',
  },
  heuristic: {
    label: 'Heuristic Generation',
    shortLabel: 'Heuristic',
    description: 'Generated using rule-based templates',
    icon: Cpu,
    color: 'text-orange-400',
    badgeVariant: 'pending',
  },
  unknown: {
    label: 'Unknown Origin',
    shortLabel: 'Unknown',
    description: 'Origin not recorded',
    icon: RefreshCw,
    color: 'text-dark-400',
    badgeVariant: 'inactive',
  },
};

// =============================================================================
// HELPER
// =============================================================================

function extractOriginMetadata(generation: Generation): OriginMetadata {
  const meta = generation.metadata || {};
  return {
    generated_by: meta.generated_by as GeneratedBy | undefined,
    ai_attempted: meta.ai_attempted as boolean | undefined,
    ai_succeeded: meta.ai_succeeded as boolean | undefined,
    fallback_used: meta.fallback_used as boolean | undefined,
    fallback_reason: meta.fallback_reason as string | undefined,
    model: meta.model as string | undefined,
    provider: meta.provider as string | undefined,
    runtime: meta.runtime as 'agent' | 'chat_completion' | undefined,
    temperature: meta.temperature as number | undefined,
    tokens_used: meta.tokens_used as number | undefined,
    generation_time_ms: meta.generation_time_ms as number | undefined,
    // PROMPT 19: Extract detailed error fields
    ai_request_started: meta.ai_request_started as boolean | undefined,
    ai_reached_gateway: meta.ai_reached_gateway as boolean | undefined,
    ai_raw_response_received: meta.ai_raw_response_received as boolean | undefined,
    ai_content_usable: meta.ai_content_usable as boolean | undefined,
    ai_error_type: meta.ai_error_type as AIErrorType | undefined,
    ai_error_stage: meta.ai_error_stage as AIErrorStage | undefined,
    ai_error_code: meta.ai_error_code as string | undefined,
    ai_error_message: meta.ai_error_message as string | undefined,
  };
}

// PROMPT 19: Human-readable error stage descriptions
function getErrorStageLabel(stage: AIErrorStage): string {
  const labels: Record<AIErrorStage, string> = {
    gateway_unreachable: 'Gateway Unreachable',
    hooks_not_configured: 'Hooks Not Configured',
    hooks_dispatch_failed: 'Hooks Dispatch Failed',
    no_response: 'No Response',
    timeout: 'Request Timeout',
    empty_response: 'Empty Response',
    invalid_shape: 'Invalid Response Format',
    validator_failed: 'Validation Failed',
    parse_failed: 'Parse Failed',
    provider_error: 'Provider Error',
    unknown: 'Unknown Error',
  };
  return labels[stage] || stage;
}

// PROMPT 19: Categorize error type for display
function getErrorTypeLabel(type: AIErrorType): { label: string; color: string } {
  switch (type) {
    case 'technical':
      return { label: 'Technical Error', color: 'text-red-400' };
    case 'unusable_response':
      return { label: 'Unusable Response', color: 'text-orange-400' };
    default:
      return { label: 'None', color: 'text-green-400' };
  }
}

function determineOrigin(meta: OriginMetadata): GeneratedBy {
  // Explicit origin
  if (meta.generated_by) return meta.generated_by;

  // Infer from flags
  if (meta.fallback_used) return 'fallback';
  if (meta.ai_succeeded) return 'ai';
  if (meta.ai_attempted && !meta.ai_succeeded) return 'fallback';

  // Default
  return 'unknown';
}

// =============================================================================
// SUB-COMPONENTS
// =============================================================================

function MetadataRow({
  label,
  value,
}: {
  label: string;
  value: string | number | undefined;
}) {
  if (value === undefined || value === null) return null;

  return (
    <div className="flex items-center justify-between py-1.5 px-2 bg-dark-900 rounded">
      <span className="text-xs text-dark-400">{label}</span>
      <span className="text-xs font-mono">{value}</span>
    </div>
  );
}

// =============================================================================
// MAIN COMPONENT
// =============================================================================

export function GenerationOriginPanel({ generation }: GenerationOriginPanelProps) {
  const meta = extractOriginMetadata(generation);
  const origin = determineOrigin(meta);
  const config = originConfig[origin];
  const Icon = config.icon;

  // Check if we have any origin metadata at all
  const hasOriginData = meta.generated_by ||
                        meta.ai_attempted !== undefined ||
                        meta.fallback_used !== undefined ||
                        meta.model ||
                        meta.provider;

  return (
    <div className="space-y-3">
      {/* Origin Header */}
      <div className={`p-3 rounded-lg border ${
        origin === 'ai' ? 'bg-primary-500/10 border-primary-500/30' :
        origin === 'fallback' ? 'bg-yellow-500/10 border-yellow-500/30' :
        origin === 'manual' ? 'bg-blue-500/10 border-blue-500/30' :
        'bg-dark-800 border-dark-700'
      }`}>
        <div className="flex items-center gap-3">
          <Icon className={`w-5 h-5 ${config.color}`} />
          <div className="flex-1">
            <div className="flex items-center gap-2">
              <span className="font-medium text-sm">{config.label}</span>
              <Badge variant={config.badgeVariant} className="text-xs">
                {origin}
              </Badge>
            </div>
            <p className="text-xs text-dark-400 mt-0.5">{config.description}</p>
          </div>
        </div>
      </div>

      {/* PROMPT 14: Clear AI Status Summary */}
      {(meta.ai_attempted !== undefined || meta.fallback_used) && (
        <div className="space-y-2">
          {/* AI Attempt Result - Clear single message */}
          {meta.ai_attempted && meta.ai_succeeded && (
            <div className="p-2 bg-green-500/10 border border-green-500/30 rounded">
              <div className="flex items-center gap-2">
                <Sparkles className="w-3 h-3 text-green-400" />
                <span className="text-xs text-green-400 font-medium">AI generation successful</span>
              </div>
            </div>
          )}

          {meta.ai_attempted && meta.ai_succeeded === false && (
            <div className="p-2 bg-red-500/10 border border-red-500/30 rounded">
              <div className="flex items-start gap-2">
                <AlertTriangle className="w-3 h-3 text-red-400 flex-shrink-0 mt-0.5" />
                <div className="flex-1">
                  <span className="text-xs text-red-400 font-medium">AI generation failed</span>
                  {/* PROMPT 19: Show detailed error info */}
                  {meta.ai_error_stage && (
                    <div className="mt-1 space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="text-xs text-dark-500">Stage:</span>
                        <span className="text-xs text-red-300 font-mono">
                          {getErrorStageLabel(meta.ai_error_stage)}
                        </span>
                      </div>
                      {meta.ai_error_type && meta.ai_error_type !== 'none' && (
                        <div className="flex items-center gap-2">
                          <span className="text-xs text-dark-500">Type:</span>
                          <span className={`text-xs font-mono ${getErrorTypeLabel(meta.ai_error_type).color}`}>
                            {getErrorTypeLabel(meta.ai_error_type).label}
                          </span>
                        </div>
                      )}
                      {meta.ai_error_message && (
                        <div className="mt-1 p-1.5 bg-dark-900 rounded">
                          <span className="text-xs text-dark-300 break-words">
                            {meta.ai_error_message.length > 150
                              ? meta.ai_error_message.substring(0, 150) + '...'
                              : meta.ai_error_message}
                          </span>
                        </div>
                      )}
                    </div>
                  )}
                  {!meta.ai_error_stage && (
                    <p className="text-xs text-dark-400 mt-0.5">
                      {meta.fallback_used ? 'Fallback template was used instead' : 'Generation may have failed'}
                    </p>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* Fallback Info - Only if not already shown above */}
          {meta.fallback_used && !meta.ai_attempted && (
            <div className="p-2 bg-yellow-500/10 border border-yellow-500/30 rounded">
              <div className="flex items-start gap-2">
                <AlertTriangle className="w-3 h-3 text-yellow-400 flex-shrink-0 mt-0.5" />
                <div>
                  <span className="text-xs text-yellow-400 font-medium">Fallback generation</span>
                  <p className="text-xs text-dark-400 mt-0.5">
                    {meta.fallback_reason === 'ai_not_configured'
                      ? 'AI was not configured - template used'
                      : meta.fallback_reason || 'Template-based generation'}
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* Detailed breakdown (collapsible style) */}
          <div className="space-y-1 text-xs">
            {meta.ai_attempted !== undefined && (
              <div className="flex items-center justify-between py-1 px-2 bg-dark-900 rounded">
                <span className="text-dark-500">AI Attempted</span>
                <span className={meta.ai_attempted ? 'text-green-400' : 'text-dark-400'}>
                  {meta.ai_attempted ? 'Yes' : 'No'}
                </span>
              </div>
            )}
            {meta.ai_attempted && meta.ai_succeeded !== undefined && (
              <div className="flex items-center justify-between py-1 px-2 bg-dark-900 rounded">
                <span className="text-dark-500">AI Succeeded</span>
                <span className={meta.ai_succeeded ? 'text-green-400' : 'text-red-400'}>
                  {meta.ai_succeeded ? 'Yes' : 'No'}
                </span>
              </div>
            )}
            {meta.fallback_used && (
              <div className="flex items-center justify-between py-1 px-2 bg-dark-900 rounded">
                <span className="text-dark-500">Fallback Used</span>
                <span className="text-yellow-400">Yes</span>
              </div>
            )}
            {meta.fallback_reason && (
              <div className="flex items-center justify-between py-1 px-2 bg-dark-900 rounded">
                <span className="text-dark-500">Fallback Reason</span>
                <span className="text-dark-300 font-mono">{meta.fallback_reason}</span>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Model/Provider Info */}
      {(meta.model || meta.provider || meta.runtime) && (
        <div className="space-y-1">
          <MetadataRow label="Model" value={meta.model} />
          <MetadataRow label="Provider" value={meta.provider} />
          <MetadataRow label="Runtime" value={meta.runtime} />
          <MetadataRow label="Temperature" value={meta.temperature} />
          <MetadataRow label="Tokens Used" value={meta.tokens_used} />
          {meta.generation_time_ms && (
            <MetadataRow label="Generation Time" value={`${meta.generation_time_ms}ms`} />
          )}
        </div>
      )}

      {/* PROMPT 19: Detailed AI Request Tracking */}
      {meta.ai_attempted && (meta.ai_request_started !== undefined ||
        meta.ai_reached_gateway !== undefined ||
        meta.ai_raw_response_received !== undefined) && (
        <div className="space-y-1">
          <div className="text-xs text-dark-500 font-medium mb-1">Request Pipeline</div>
          {meta.ai_request_started !== undefined && (
            <div className="flex items-center justify-between py-1 px-2 bg-dark-900 rounded">
              <span className="text-dark-500 text-xs">Request Started</span>
              <span className={meta.ai_request_started ? 'text-green-400 text-xs' : 'text-red-400 text-xs'}>
                {meta.ai_request_started ? 'Yes' : 'No'}
              </span>
            </div>
          )}
          {meta.ai_reached_gateway !== undefined && (
            <div className="flex items-center justify-between py-1 px-2 bg-dark-900 rounded">
              <span className="text-dark-500 text-xs">Reached Gateway</span>
              <span className={meta.ai_reached_gateway ? 'text-green-400 text-xs' : 'text-red-400 text-xs'}>
                {meta.ai_reached_gateway ? 'Yes' : 'No'}
              </span>
            </div>
          )}
          {meta.ai_raw_response_received !== undefined && (
            <div className="flex items-center justify-between py-1 px-2 bg-dark-900 rounded">
              <span className="text-dark-500 text-xs">Response Received</span>
              <span className={meta.ai_raw_response_received ? 'text-green-400 text-xs' : 'text-red-400 text-xs'}>
                {meta.ai_raw_response_received ? 'Yes' : 'No'}
              </span>
            </div>
          )}
          {meta.ai_content_usable !== undefined && (
            <div className="flex items-center justify-between py-1 px-2 bg-dark-900 rounded">
              <span className="text-dark-500 text-xs">Content Usable</span>
              <span className={meta.ai_content_usable ? 'text-green-400 text-xs' : 'text-red-400 text-xs'}>
                {meta.ai_content_usable ? 'Yes' : 'No'}
              </span>
            </div>
          )}
        </div>
      )}

      {/* No origin data available */}
      {!hasOriginData && (
        <p className="text-xs text-dark-500 text-center py-2">
          No origin metadata recorded for this generation
        </p>
      )}
    </div>
  );
}
