import { createLogger } from '../utils/logger.js';
import { getServices } from '../services/index.js';
import { getAIClient, type AgentAIResponse } from './AIClient.js';
import { getValidator } from './Validator.js';
import { agentTemplate } from './templates/index.js';
import { ForbiddenError } from '../utils/errors.js';
import {
  canCreateAgentAutonomously,
  requiresApprovalForAgentCreation,
} from '../config/autonomy.js';
import {
  createTraceability,
  toStoredTraceability,
  toOriginMetadata,
  MATERIALIZATION_STATUS,
  type FullGenerationTraceability,
} from './traceability.js';
import {
  materializeAgent,
  computeMaterializationStatus,
  getStatusDescription,
  type MaterializationTraceability,
  type AgentMaterializationStatus,
} from './AgentMaterialization.js';
import type { GenerationRequest, GenerationOutput } from './types.js';
import type { AgentType } from '../types/domain.js';

export type GenerationSource = 'api' | 'system' | 'orchestrator';

const logger = createLogger('AgentGenerator');

/**
 * Content stored in generation.generatedContent for agents
 * This is the source of truth used during activation
 */
interface AgentGeneratedContent {
  type: AgentType;
  capabilities: string[];
  config: Record<string, unknown>;
  generatedBy: 'ai' | 'template';
  /** BLOQUE 7: Trazabilidad explícita de generación */
  _traceability?: Record<string, unknown>;
  /** BLOQUE 9: Trazabilidad de materialización */
  _materialization_trace?: MaterializationTraceability;
  /** BLOQUE 9: Estado de materialización */
  _materialization_status?: AgentMaterializationStatus;
  [key: string]: unknown; // Allow index signature for Record<string, unknown> compatibility
}

export class AgentGenerator {
  async generate(request: GenerationRequest, source: GenerationSource = 'api'): Promise<GenerationOutput> {
    // Check autonomy permissions for non-human sources
    if (source !== 'api') {
      if (!canCreateAgentAutonomously()) {
        throw new ForbiddenError('Autonomous agent generation is disabled by autonomy policy');
      }
    }

    const { generationService } = getServices();
    const aiClient = getAIClient();
    const validator = getValidator();

    const generation = await generationService.create({
      type: 'agent',
      name: request.name,
      description: request.description,
      prompt: request.prompt,
    });

    try {
      let agentType: AgentType = 'general';
      let capabilities: string[] = [];
      let config: Record<string, unknown> = {};
      let generatedBy: 'ai' | 'template' = 'template';

      // BLOQUE 7: Build traceability throughout the flow
      const trace = createTraceability().aiRequested();

      // Helper to generate via template - returns the values
      const generateTemplate = (): { type: AgentType; capabilities: string[]; config: Record<string, unknown> } => {
        const template = agentTemplate(
          request.name,
          request.description,
          'specialist',
          request.requirements || []
        );
        return {
          type: template.type,
          capabilities: template.capabilities,
          config: template.config,
        };
      };

      const aiConfigured = aiClient.isConfigured();
      trace.aiAvailable(aiConfigured);

      if (aiConfigured) {
        // Try AI generation with user's prompt
        trace.aiAttempted();
        try {
          const response = await aiClient.generate<AgentAIResponse>({
            type: 'agent',
            name: request.name,
            description: request.description,
            prompt: request.prompt,
            requirements: request.requirements,
          });

          agentType = response.parsed.type || 'general';
          capabilities = response.parsed.capabilities || [];
          config = response.parsed.config || {};
          generatedBy = 'ai';

          // Record AI success with usage
          trace.aiResult(true, 'claude', response.usage);

          logger.debug({
            name: request.name,
            type: agentType,
            capCount: capabilities.length,
          }, 'Agent generated by AI');
        } catch (aiErr) {
          // AI failed (connectivity, parsing, etc.) - fallback to template
          trace.aiResult(false).usedFallback('ai_request_failed', 'agentTemplate');

          logger.warn({ name: request.name, err: aiErr }, 'AI generation failed, using template fallback');
          const tmpl = generateTemplate();
          agentType = tmpl.type;
          capabilities = tmpl.capabilities;
          config = tmpl.config;
          generatedBy = 'template';
        }
      } else {
        trace.usedFallback('ai_not_configured', 'agentTemplate');

        logger.info({ name: request.name }, 'Using template (AI not configured)');
        const tmpl = generateTemplate();
        agentType = tmpl.type;
        capabilities = tmpl.capabilities;
        config = tmpl.config;
        generatedBy = 'template';
      }

      // Validate the generated content
      const validation = validator.validateAgent({
        name: request.name,
        type: agentType,
        capabilities,
        config,
      });

      // Record validation result in traceability
      trace.validated(validation.valid, validation.errors, validation.warnings);

      if (!validation.valid) {
        await generationService.markFailed(generation.id, validation.errors.join('; '));
        return {
          files: [],
          metadata: { validation, generationId: generation.id, _traceability: toStoredTraceability(trace.build()) },
        };
      }

      // BLOQUE 7: Mark materialization gap explicitly
      trace.materialization(false, MATERIALIZATION_STATUS.agent.gap);

      // Store the full generated content for activation (with traceability)
      const generatedContent: AgentGeneratedContent = {
        type: agentType,
        capabilities,
        config,
        generatedBy,
        _traceability: toStoredTraceability(trace.build()),
      };

      // Extract origin metadata for frontend display
      const originMetadata = toOriginMetadata(trace.build());

      await generationService.markGenerated(
        generation.id,
        generatedContent,
        `agents/${request.name}`,
        originMetadata
      );

      // Always go to pending_approval first (required by FSM)
      await generationService.markPendingApproval(generation.id, {
        valid: true,
        warnings: validation.warnings,
        type: agentType,
        capabilitiesCount: capabilities.length,
        generatedBy,
      });

      logger.info({
        generationId: generation.id,
        name: request.name,
        type: agentType,
        generatedBy,
        requiresApproval: this.requiresApproval(source),
      }, 'Agent generation completed');

      return {
        files: [],
        metadata: {
          generationId: generation.id,
          type: agentType,
          capabilities,
          config,
          validation,
          generatedBy,
        },
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Unknown error';
      await generationService.markFailed(generation.id, message);
      throw err;
    }
  }

  async activate(generationId: string): Promise<void> {
    const { generationService, agentService } = getServices();

    const generation = await generationService.getById(generationId);

    if (generation.status !== 'approved') {
      throw new Error('Can only activate approved generations');
    }

    // Use the stored content directly (no regeneration)
    const content = generation.generatedContent as AgentGeneratedContent;

    if (!content || !content.type) {
      throw new Error('Missing or invalid generated content for agent');
    }

    // BLOQUE 9: Attempt real materialization (workspace + config files)
    const materializationTrace = await materializeAgent(
      generation.name,
      content.type,
      generation.description,
      content.capabilities,
      content.config,
      'activation'
    );

    // Compute final materialization status
    const materializationStatus = computeMaterializationStatus(
      generation.name,
      true, // will have DB record after create
      true, // generation is being activated
      undefined // no OpenClaw session yet
    );

    // Create agent in DB using stored content
    // BLOQUE 9: Now includes actual materialization status
    const agent = await agentService.create({
      name: generation.name,
      description: generation.description,
      type: content.type,
      capabilities: content.capabilities,
      config: {
        ...content.config,
        // BLOQUE 9: Store full materialization status
        _materialization: {
          state: materializationStatus.state,
          db_record: true,
          workspace_exists: materializationStatus.workspace_exists,
          config_written: materializationStatus.config_written,
          runtime_possible: materializationStatus.runtime_possible,
          openclaw_session: false,
          materialization_attempted_at: materializationTrace.attempted_at,
          materialization_succeeded: materializationTrace.steps_failed.length === 0,
          materialization_reason: materializationTrace.gap,
          target_workspace: materializationStatus.target_workspace,
          // Keep BLOQUE 7 gap for compatibility
          gap: MATERIALIZATION_STATUS.agent.gap,
          activated_at: Date.now(),
        },
      },
    });

    // Update generation metadata with resourceId for frontend link
    await generationService.updateMetadata(generationId, {
      resourceId: agent.id,
      agentId: agent.id,
      resourceStatus: agent.status,
    });

    await generationService.activate(generationId);

    // BLOQUE 9: Explicit logging of real state
    logger.info({
      generationId,
      name: generation.name,
      type: content.type,
      generatedBy: content.generatedBy,
      // BLOQUE 9: Real materialization status
      lifecycle_state: materializationStatus.state,
      materialization: {
        attempted: true,
        succeeded: materializationTrace.steps_failed.length === 0,
        steps_completed: materializationTrace.steps_completed,
        steps_failed: materializationTrace.steps_failed,
        workspace_exists: materializationStatus.workspace_exists,
        config_written: materializationStatus.config_written,
        runtime_ready: false, // OpenClaw session not started
      },
      status_description: getStatusDescription(materializationStatus),
    }, 'Agent activated with materialization');
  }

  // Check if generation requires approval
  requiresApproval(source: GenerationSource): boolean {
    if (source === 'api') return false; // Human-initiated via API doesn't need approval
    return requiresApprovalForAgentCreation();
  }
}

let agentGeneratorInstance: AgentGenerator | null = null;

export function getAgentGenerator(): AgentGenerator {
  if (!agentGeneratorInstance) {
    agentGeneratorInstance = new AgentGenerator();
  }
  return agentGeneratorInstance;
}
