import { createLogger } from '../utils/logger.js';
import { getServices } from '../services/index.js';
import { getAIClient, type AgentAIResponse } from './AIClient.js';
import { getValidator } from './Validator.js';
import { agentTemplate } from './templates/index.js';
import { ForbiddenError } from '../utils/errors.js';
import {
  canCreateAgentAutonomously,
  requiresApprovalForAgentCreation,
} from '../config/autonomy.js';
import type { GenerationRequest, GenerationOutput } from './types.js';
import type { AgentType } from '../types/domain.js';

export type GenerationSource = 'api' | 'system' | 'orchestrator';

const logger = createLogger('AgentGenerator');

/**
 * Content stored in generation.generatedContent for agents
 * This is the source of truth used during activation
 */
interface AgentGeneratedContent {
  type: AgentType;
  capabilities: string[];
  config: Record<string, unknown>;
  generatedBy: 'ai' | 'template';
  [key: string]: unknown; // Allow index signature for Record<string, unknown> compatibility
}

export class AgentGenerator {
  async generate(request: GenerationRequest, source: GenerationSource = 'api'): Promise<GenerationOutput> {
    // Check autonomy permissions for non-human sources
    if (source !== 'api') {
      if (!canCreateAgentAutonomously()) {
        throw new ForbiddenError('Autonomous agent generation is disabled by autonomy policy');
      }
    }

    const { generationService } = getServices();
    const aiClient = getAIClient();
    const validator = getValidator();

    const generation = await generationService.create({
      type: 'agent',
      name: request.name,
      description: request.description,
      prompt: request.prompt,
    });

    try {
      let agentType: AgentType = 'general';
      let capabilities: string[] = [];
      let config: Record<string, unknown> = {};
      let generatedBy: 'ai' | 'template' = 'template';

      // Helper to generate via template - returns the values
      const generateTemplate = (): { type: AgentType; capabilities: string[]; config: Record<string, unknown> } => {
        const template = agentTemplate(
          request.name,
          request.description,
          'specialist',
          request.requirements || []
        );
        return {
          type: template.type,
          capabilities: template.capabilities,
          config: template.config,
        };
      };

      if (aiClient.isConfigured()) {
        // Try AI generation with user's prompt
        try {
          const response = await aiClient.generate<AgentAIResponse>({
            type: 'agent',
            name: request.name,
            description: request.description,
            prompt: request.prompt,
            requirements: request.requirements,
          });

          agentType = response.parsed.type || 'general';
          capabilities = response.parsed.capabilities || [];
          config = response.parsed.config || {};
          generatedBy = 'ai';

          logger.debug({
            name: request.name,
            type: agentType,
            capCount: capabilities.length,
          }, 'Agent generated by AI');
        } catch (aiErr) {
          // AI failed (connectivity, parsing, etc.) - fallback to template
          logger.warn({ name: request.name, err: aiErr }, 'AI generation failed, using template fallback');
          const tmpl = generateTemplate();
          agentType = tmpl.type;
          capabilities = tmpl.capabilities;
          config = tmpl.config;
          generatedBy = 'template';
        }
      } else {
        logger.info({ name: request.name }, 'Using template (AI not configured)');
        const tmpl = generateTemplate();
        agentType = tmpl.type;
        capabilities = tmpl.capabilities;
        config = tmpl.config;
        generatedBy = 'template';
      }

      // Validate the generated content
      const validation = validator.validateAgent({
        name: request.name,
        type: agentType,
        capabilities,
        config,
      });

      if (!validation.valid) {
        await generationService.markFailed(generation.id, validation.errors.join('; '));
        return {
          files: [],
          metadata: { validation, generationId: generation.id },
        };
      }

      // Store the full generated content for activation
      const generatedContent: AgentGeneratedContent = {
        type: agentType,
        capabilities,
        config,
        generatedBy,
      };

      await generationService.markGenerated(generation.id, generatedContent, `agents/${request.name}`);

      // Respect approval policy based on source
      if (this.requiresApproval(source)) {
        await generationService.markPendingApproval(generation.id, {
          valid: true,
          warnings: validation.warnings,
          type: agentType,
          capabilitiesCount: capabilities.length,
          generatedBy,
        });
        logger.info({
          generationId: generation.id,
          name: request.name,
          type: agentType,
          generatedBy,
        }, 'Agent generation completed - pending approval');
      } else {
        // API source (human) - auto-approve
        await generationService.approve(generation.id, 'api-auto');
        logger.info({
          generationId: generation.id,
          name: request.name,
          type: agentType,
          generatedBy,
        }, 'Agent generation completed - auto-approved (human source)');
      }

      return {
        files: [],
        metadata: {
          generationId: generation.id,
          type: agentType,
          capabilities,
          config,
          validation,
          generatedBy,
        },
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Unknown error';
      await generationService.markFailed(generation.id, message);
      throw err;
    }
  }

  async activate(generationId: string): Promise<void> {
    const { generationService, agentService } = getServices();

    const generation = await generationService.getById(generationId);

    if (generation.status !== 'approved') {
      throw new Error('Can only activate approved generations');
    }

    // Use the stored content directly (no regeneration)
    const content = generation.generatedContent as AgentGeneratedContent;

    if (!content || !content.type) {
      throw new Error('Missing or invalid generated content for agent');
    }

    // Create agent in DB using stored content
    await agentService.create({
      name: generation.name,
      description: generation.description,
      type: content.type,
      capabilities: content.capabilities,
      config: content.config,
    });

    await generationService.activate(generationId);

    logger.info({
      generationId,
      name: generation.name,
      type: content.type,
      generatedBy: content.generatedBy,
    }, 'Agent activated from stored content');
  }

  // Check if generation requires approval
  requiresApproval(source: GenerationSource): boolean {
    if (source === 'api') return false; // Human-initiated via API doesn't need approval
    return requiresApprovalForAgentCreation();
  }
}

let agentGeneratorInstance: AgentGenerator | null = null;

export function getAgentGenerator(): AgentGenerator {
  if (!agentGeneratorInstance) {
    agentGeneratorInstance = new AgentGenerator();
  }
  return agentGeneratorInstance;
}
