import { createLogger } from '../utils/logger.js';
import { getServices } from '../services/index.js';
import { getWorkspaceSync } from '../openclaw/index.js';
import { getAIClient, type SkillAIResponse } from './AIClient.js';
import { getValidator } from './Validator.js';
import { skillTemplate } from './templates/index.js';
import { ForbiddenError } from '../utils/errors.js';
import {
  canGenerateSkillAutonomously,
  requiresApprovalForSkillGeneration,
} from '../config/autonomy.js';
import {
  createTraceability,
  toStoredTraceability,
  toOriginMetadata,
  MATERIALIZATION_STATUS,
} from './traceability.js';
import type { GenerationRequest, GeneratedFile, GenerationOutput } from './types.js';

const logger = createLogger('SkillGenerator');

export type GenerationSource = 'api' | 'system' | 'orchestrator';

/**
 * Content stored in generation.generatedContent for skills
 * This stores the ACTUAL file contents for activation
 */
interface SkillGeneratedContent {
  files: Record<string, string>; // path -> content (actual file contents)
  capabilities: string[];
  generatedBy: 'ai' | 'template';
  /** BLOQUE 7: Explicit generation traceability */
  _traceability?: Record<string, unknown>;
  [key: string]: unknown; // Allow index signature for Record<string, unknown> compatibility
}

export class SkillGenerator {
  async generate(request: GenerationRequest, source: GenerationSource = 'api'): Promise<GenerationOutput> {
    // Check autonomy permissions for non-human sources
    if (source !== 'api') {
      if (!canGenerateSkillAutonomously()) {
        throw new ForbiddenError('Autonomous skill generation is disabled by autonomy policy');
      }
    }

    const { generationService } = getServices();
    const aiClient = getAIClient();
    const validator = getValidator();

    // BLOQUE 7: Initialize traceability builder
    const trace = createTraceability().aiRequested();
    const aiConfigured = aiClient.isConfigured();
    trace.aiAvailable(aiConfigured);

    // Create generation record
    const generation = await generationService.create({
      type: 'skill',
      name: request.name,
      description: request.description,
      prompt: request.prompt,
    });

    try {
      let files: GeneratedFile[];
      let capabilities: string[] = [];
      let generatedBy: 'ai' | 'template' = 'template';

      // Helper to generate via template - returns the values
      const generateTemplate = (): { files: GeneratedFile[]; capabilities: string[] } => {
        const templateFiles = skillTemplate(
          request.name,
          request.description,
          request.requirements || ['default']
        );
        return {
          files: Object.entries(templateFiles).map(([path, content]) => ({
            path,
            content,
          })),
          capabilities: request.requirements || ['default'],
        };
      };

      if (aiConfigured) {
        // Try AI generation with user's prompt
        trace.aiAttempted();
        try {
          const response = await aiClient.generate<SkillAIResponse>({
            type: 'skill',
            name: request.name,
            description: request.description,
            prompt: request.prompt,
            requirements: request.requirements,
          });

          files = Object.entries(response.parsed.files).map(([path, content]) => ({
            path,
            content,
          }));
          capabilities = response.parsed.capabilities || [];
          generatedBy = 'ai';

          // BLOQUE 7 + PROMPT 16B: Mark AI success with usage and runtime info
          trace.aiResult(true, 'claude', response.usage, 'openclaw', response.runtime);

          logger.debug({
            name: request.name,
            fileCount: files.length,
            capCount: capabilities.length,
          }, 'Skill generated by AI');
        } catch (aiErr) {
          // AI failed (connectivity, parsing, etc.) - fallback to template
          // BLOQUE 7: Mark AI failure and fallback reason
          trace.aiResult(false).usedFallback('ai_request_failed', 'skillTemplate');

          logger.warn({ name: request.name, err: aiErr }, 'AI generation failed, using template fallback');
          const tmpl = generateTemplate();
          files = tmpl.files;
          capabilities = tmpl.capabilities;
          generatedBy = 'template';
        }
      } else {
        // BLOQUE 7: AI not configured - explicit fallback
        trace.usedFallback('ai_not_configured', 'skillTemplate');

        logger.info({ name: request.name }, 'Using template (AI not configured)');
        const tmpl = generateTemplate();
        files = tmpl.files;
        capabilities = tmpl.capabilities;
        generatedBy = 'template';
      }

      // Validate
      const validation = validator.validateSkill(files);

      // BLOQUE 7: Record validation result in traceability
      trace.validated(validation.valid, validation.errors, validation.warnings);

      if (!validation.valid) {
        await generationService.markFailed(generation.id, validation.errors.join('; '));
        return {
          files: [],
          metadata: { validation, generationId: generation.id },
        };
      }

      // Store ACTUAL file contents for activation (not just metadata)
      const filesMap: Record<string, string> = {};
      for (const f of files) {
        filesMap[f.path] = f.content;
      }

      // BLOQUE 7: Mark materialization status (files will be written, but not loaded in OpenClaw yet)
      trace.materialization(false, MATERIALIZATION_STATUS.skill.gap);

      const generatedContent: SkillGeneratedContent = {
        files: filesMap,
        capabilities,
        generatedBy,
        // BLOQUE 7: Store full traceability
        _traceability: toStoredTraceability(trace.build()),
      };

      // Extract origin metadata for frontend display
      const originMetadata = toOriginMetadata(trace.build());

      const targetPath = `skills/${request.name}`;
      await generationService.markGenerated(generation.id, generatedContent, targetPath, originMetadata);

      // Always go to pending_approval first (required by FSM)
      await generationService.markPendingApproval(generation.id, {
        valid: true,
        warnings: validation.warnings,
        filesCount: files.length,
        generatedBy,
      });

      logger.info({
        generationId: generation.id,
        name: request.name,
        fileCount: files.length,
        generatedBy,
        requiresApproval: this.requiresApproval(source),
      }, 'Skill generation completed');

      return {
        files,
        metadata: {
          generationId: generation.id,
          capabilities,
          validation,
          generatedBy,
        },
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Unknown error';
      await generationService.markFailed(generation.id, message);
      throw err;
    }
  }

  async activate(generationId: string): Promise<void> {
    const { generationService, skillService } = getServices();
    const workspaceSync = getWorkspaceSync();

    const generation = await generationService.getById(generationId);

    if (generation.status !== 'approved') {
      throw new Error('Can only activate approved generations');
    }

    // Use STORED content directly (no regeneration!)
    const content = generation.generatedContent as SkillGeneratedContent;

    if (!content || !content.files) {
      throw new Error('Missing or invalid generated content for skill');
    }

    // Write stored files to workspace
    const skillPath = await workspaceSync.writeSkill(generation.name, content.files);

    // BLOQUE 7: EXPLICIT GAP DOCUMENTATION
    // =====================================
    // This creates:
    // 1. Files written to workspace (skill files on disk) ✓
    // 2. DB record in skills table ("ficha") ✓
    //
    // This does NOT create:
    // - OpenClaw skill loaded in runtime (loaded on-demand when agent needs it)
    // - No smoke test or syntax verification before activation
    //
    // The skill is NOT operationally materialized until OpenClaw loads it.
    // =====================================

    // Create skill in DB
    const skill = await skillService.create({
      name: generation.name,
      description: generation.description,
      path: skillPath,
      capabilities: content.capabilities,
    });

    // Update generation metadata with resourceId for frontend link
    await generationService.updateMetadata(generationId, {
      resourceId: skill.id,
      skillId: skill.id,
      resourceStatus: skill.status,
    });

    // Mark generation as active
    await generationService.activate(generationId);

    logger.info({
      generationId,
      name: generation.name,
      fileCount: Object.keys(content.files).length,
      generatedBy: content.generatedBy,
      // BLOQUE 7: Explicit materialization status
      materialization: {
        db_record: true,
        files_written: true,
        openclaw_loaded: false,
        gap: MATERIALIZATION_STATUS.skill.gap,
      },
    }, 'Skill activated from stored content');
  }

  // Check if generation requires approval
  requiresApproval(source: GenerationSource): boolean {
    if (source === 'api') return false; // Human-initiated via API doesn't need approval
    return requiresApprovalForSkillGeneration();
  }
}

let skillGeneratorInstance: SkillGenerator | null = null;

export function getSkillGenerator(): SkillGenerator {
  if (!skillGeneratorInstance) {
    skillGeneratorInstance = new SkillGenerator();
  }
  return skillGeneratorInstance;
}
