import { createLogger } from '../utils/logger.js';
import { getServices } from '../services/index.js';
import { getWorkspaceSync } from '../openclaw/index.js';
import { getAIClient, type ToolAIResponse } from './AIClient.js';
import { getValidator } from './Validator.js';
import { toolTemplateShell, toolTemplatePython } from './templates/index.js';
import { ForbiddenError } from '../utils/errors.js';
import {
  canGenerateToolAutonomously,
  requiresApprovalForToolGeneration,
} from '../config/autonomy.js';
import type { GenerationRequest, GenerationOutput } from './types.js';

export type GenerationSource = 'api' | 'system' | 'orchestrator';

const logger = createLogger('ToolGenerator');

/**
 * Content stored in generation.generatedContent for tools
 * This stores the ACTUAL script content for activation
 */
interface ToolGeneratedContent {
  type: 'sh' | 'py';
  content: string; // Actual script content
  inputSchema?: Record<string, unknown>;
  outputSchema?: Record<string, unknown>;
  generatedBy: 'ai' | 'template';
  [key: string]: unknown; // Allow index signature for Record<string, unknown> compatibility
}

export class ToolGenerator {
  async generate(request: GenerationRequest, source: GenerationSource = 'api'): Promise<GenerationOutput> {
    // Check autonomy permissions for non-human sources
    if (source !== 'api') {
      if (!canGenerateToolAutonomously()) {
        throw new ForbiddenError('Autonomous tool generation is disabled by autonomy policy');
      }
    }

    const { generationService } = getServices();
    const aiClient = getAIClient();
    const validator = getValidator();

    const generation = await generationService.create({
      type: 'tool',
      name: request.name,
      description: request.description,
      prompt: request.prompt,
    });

    try {
      let content: string;
      let toolType: 'sh' | 'py' = 'sh';
      let inputSchema: Record<string, unknown> | undefined;
      let outputSchema: Record<string, unknown> | undefined;
      let generatedBy: 'ai' | 'template' = 'template';

      // Helper to generate via template - returns the values
      const generateTemplate = (): { content: string; toolType: 'sh' | 'py' } => {
        const usePython = request.requirements?.some(r =>
          r.toLowerCase().includes('python') || r.toLowerCase().includes('json')
        );
        const type: 'sh' | 'py' = usePython ? 'py' : 'sh';
        const script = type === 'py'
          ? toolTemplatePython(request.name, request.description)
          : toolTemplateShell(request.name, request.description);
        return { content: script, toolType: type };
      };

      if (aiClient.isConfigured()) {
        // Try AI generation with user's prompt
        try {
          const response = await aiClient.generate<ToolAIResponse>({
            type: 'tool',
            name: request.name,
            description: request.description,
            prompt: request.prompt,
            requirements: request.requirements,
          });

          content = response.parsed.content;
          toolType = response.parsed.type || 'sh';
          inputSchema = response.parsed.inputSchema;
          outputSchema = response.parsed.outputSchema;
          generatedBy = 'ai';

          logger.debug({
            name: request.name,
            type: toolType,
            contentLength: content.length,
          }, 'Tool generated by AI');
        } catch (aiErr) {
          // AI failed (connectivity, parsing, etc.) - fallback to template
          logger.warn({ name: request.name, err: aiErr }, 'AI generation failed, using template fallback');
          const tmpl = generateTemplate();
          content = tmpl.content;
          toolType = tmpl.toolType;
          generatedBy = 'template';
        }
      } else {
        logger.info({ name: request.name }, 'Using template (AI not configured)');
        const tmpl = generateTemplate();
        content = tmpl.content;
        toolType = tmpl.toolType;
        generatedBy = 'template';
      }

      // Validate
      const validation = validator.validateTool(content, toolType);

      if (!validation.valid) {
        await generationService.markFailed(generation.id, validation.errors.join('; '));
        return {
          files: [],
          metadata: { validation, generationId: generation.id },
        };
      }

      // Store ACTUAL content for activation (not just metadata!)
      const generatedContent: ToolGeneratedContent = {
        type: toolType,
        content, // The actual script content
        inputSchema,
        outputSchema,
        generatedBy,
      };

      const targetPath = `tools/${request.name}.${toolType}`;
      await generationService.markGenerated(generation.id, generatedContent, targetPath);

      // Always go to pending_approval first (required by FSM)
      await generationService.markPendingApproval(generation.id, {
        valid: true,
        warnings: validation.warnings,
        type: toolType,
        generatedBy,
      });

      logger.info({
        generationId: generation.id,
        name: request.name,
        type: toolType,
        generatedBy,
        requiresApproval: this.requiresApproval(source),
      }, 'Tool generation completed');

      return {
        files: [{ path: `${request.name}.${toolType}`, content }],
        metadata: {
          generationId: generation.id,
          type: toolType,
          inputSchema,
          outputSchema,
          validation,
          generatedBy,
        },
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Unknown error';
      await generationService.markFailed(generation.id, message);
      throw err;
    }
  }

  async activate(generationId: string): Promise<void> {
    const { generationService, toolService } = getServices();
    const workspaceSync = getWorkspaceSync();

    const generation = await generationService.getById(generationId);

    if (generation.status !== 'approved') {
      throw new Error('Can only activate approved generations');
    }

    // Use STORED content directly (no regeneration!)
    const content = generation.generatedContent as ToolGeneratedContent;

    if (!content || !content.content) {
      throw new Error('Missing or invalid generated content for tool');
    }

    // Write stored content to workspace
    const toolPath = await workspaceSync.writeTool(generation.name, content.content, content.type);

    // Create tool in DB
    await toolService.create({
      name: generation.name,
      description: generation.description,
      path: toolPath,
      type: 'script',
      inputSchema: content.inputSchema,
      outputSchema: content.outputSchema,
    });

    await generationService.activate(generationId);

    logger.info({
      generationId,
      name: generation.name,
      type: content.type,
      generatedBy: content.generatedBy,
    }, 'Tool activated from stored content');
  }

  // Check if generation requires approval
  requiresApproval(source: GenerationSource): boolean {
    if (source === 'api') return false; // Human-initiated via API doesn't need approval
    return requiresApprovalForToolGeneration();
  }
}

let toolGeneratorInstance: ToolGenerator | null = null;

export function getToolGenerator(): ToolGenerator {
  if (!toolGeneratorInstance) {
    toolGeneratorInstance = new ToolGenerator();
  }
  return toolGeneratorInstance;
}
