/**
 * Job Resolution Service
 *
 * Handles blocked job resolution:
 * - Creates approvals for resource generation
 * - Triggers tool/skill creation
 * - Auto-retries after resolution
 * - Tracks resolution history
 */

import { nanoid } from 'nanoid';
import { createLogger } from '../utils/logger.js';
import { nowTimestamp } from '../utils/helpers.js';
import { getServices } from '../services/index.js';
import { getJobDispatcherService } from './JobDispatcherService.js';
import type { JobBlocked, BlockingSuggestion, JobRecord } from './types.js';

const logger = createLogger('JobResolution');

// ============================================================================
// TYPES
// ============================================================================

export interface ResolutionRequest {
  jobId: string;
  suggestion: BlockingSuggestion;
  autoApprove?: boolean;
}

export interface ResolutionResult {
  success: boolean;
  approvalId?: string;
  generationId?: string;
  error?: string;
  autoRetryScheduled?: boolean;
}

export interface RetryConfig {
  maxRetries: number;
  delayMs: number;
  backoffMultiplier: number;
  retryOnErrors: string[];
}

const DEFAULT_RETRY_CONFIG: RetryConfig = {
  maxRetries: 3,
  delayMs: 2000,
  backoffMultiplier: 2,
  retryOnErrors: ['timeout', 'rate_limited', 'resource_error'],
};

// Pending auto-retries: jobId → timeoutId
const pendingRetries = new Map<string, NodeJS.Timeout>();

// ============================================================================
// RESOLUTION FUNCTIONS
// ============================================================================

/**
 * Resolve a blocked job by acting on a suggestion
 */
export async function resolveBlockedJob(
  request: ResolutionRequest
): Promise<ResolutionResult> {
  const { jobId, suggestion, autoApprove } = request;
  const dispatcher = getJobDispatcherService();
  const job = dispatcher.getJob(jobId);

  if (!job) {
    return { success: false, error: 'Job not found' };
  }

  if (job.status !== 'blocked') {
    return { success: false, error: `Job is not blocked (status: ${job.status})` };
  }

  logger.info({ jobId, suggestionType: suggestion.type }, 'Resolving blocked job');

  try {
    switch (suggestion.type) {
      case 'create_tool':
        return await handleCreateTool(job, suggestion, autoApprove);

      case 'create_skill':
        return await handleCreateSkill(job, suggestion, autoApprove);

      case 'request_permission':
        return await handleRequestPermission(job, suggestion);

      case 'provide_data':
        return { success: false, error: 'Manual data provision required' };

      case 'manual_action':
        return { success: false, error: 'Manual action required' };

      default:
        return { success: false, error: `Unknown suggestion type: ${suggestion.type}` };
    }
  } catch (err) {
    logger.error({ err, jobId }, 'Failed to resolve blocked job');
    return { success: false, error: err instanceof Error ? err.message : 'Unknown error' };
  }
}

/**
 * Handle tool creation suggestion
 */
async function handleCreateTool(
  job: JobRecord,
  suggestion: BlockingSuggestion,
  autoApprove?: boolean
): Promise<ResolutionResult> {
  const { generationService, approvalService } = getServices();

  const prompt = suggestion.generationPrompt ||
    `Create a tool named "${suggestion.target}" that ${suggestion.description}`;

  const generation = await generationService.create({
    type: 'tool',
    name: suggestion.target,
    description: suggestion.description,
    prompt,
    metadata: {
      sourceJobId: job.id,
      sourceTaskId: job.payload.taskId,
      autoGenerated: true,
    },
  });

  if (!autoApprove) {
    const approval = await approvalService.create({
      type: 'generation',
      resourceId: generation.id,
      metadata: {
        generationType: 'tool',
        targetName: suggestion.target,
        sourceJobId: job.id,
        onApprove: 'retry_job',
      },
    });

    logger.info({ jobId: job.id, approvalId: approval.id }, 'Created approval for tool generation');

    return {
      success: true,
      generationId: generation.id,
      approvalId: approval.id,
      autoRetryScheduled: false,
    };
  }

  logger.info({ jobId: job.id, generationId: generation.id }, 'Auto-generating tool');

  return {
    success: true,
    generationId: generation.id,
    autoRetryScheduled: true,
  };
}

/**
 * Handle skill creation suggestion
 */
async function handleCreateSkill(
  job: JobRecord,
  suggestion: BlockingSuggestion,
  autoApprove?: boolean
): Promise<ResolutionResult> {
  const { generationService, approvalService } = getServices();

  const prompt = suggestion.generationPrompt ||
    `Create a skill named "${suggestion.target}" that ${suggestion.description}`;

  const generation = await generationService.create({
    type: 'skill',
    name: suggestion.target,
    description: suggestion.description,
    prompt,
    metadata: {
      sourceJobId: job.id,
      sourceTaskId: job.payload.taskId,
      autoGenerated: true,
    },
  });

  if (!autoApprove) {
    const approval = await approvalService.create({
      type: 'generation',
      resourceId: generation.id,
      metadata: {
        generationType: 'skill',
        targetName: suggestion.target,
        sourceJobId: job.id,
        onApprove: 'retry_job',
      },
    });

    return {
      success: true,
      generationId: generation.id,
      approvalId: approval.id,
      autoRetryScheduled: false,
    };
  }

  return {
    success: true,
    generationId: generation.id,
    autoRetryScheduled: true,
  };
}

/**
 * Handle permission request
 */
async function handleRequestPermission(
  job: JobRecord,
  suggestion: BlockingSuggestion
): Promise<ResolutionResult> {
  const { approvalService } = getServices();

  const approval = await approvalService.create({
    type: 'permission',
    metadata: {
      agentId: job.payload.agent.agentId,
      permissionTarget: suggestion.target,
      description: suggestion.description,
      sourceJobId: job.id,
      onApprove: 'grant_and_retry',
    },
  });

  return {
    success: true,
    approvalId: approval.id,
    autoRetryScheduled: false,
  };
}

// ============================================================================
// RETRY SYSTEM
// ============================================================================

/**
 * Schedule automatic retry for a job
 */
export function scheduleRetry(
  jobId: string,
  delayMs: number,
  reason: string
): void {
  // Cancel any existing retry
  cancelPendingRetry(jobId);

  logger.info({ jobId, delayMs, reason }, 'Scheduling job retry');

  const timeout = setTimeout(async () => {
    pendingRetries.delete(jobId);
    await executeRetry(jobId, reason);
  }, delayMs);

  pendingRetries.set(jobId, timeout);
}

/**
 * Cancel pending retry
 */
export function cancelPendingRetry(jobId: string): boolean {
  const timeout = pendingRetries.get(jobId);
  if (timeout) {
    clearTimeout(timeout);
    pendingRetries.delete(jobId);
    return true;
  }
  return false;
}

/**
 * Execute retry
 */
async function executeRetry(jobId: string, reason: string): Promise<void> {
  const dispatcher = getJobDispatcherService();

  logger.info({ jobId, reason }, 'Executing scheduled retry');

  const result = await dispatcher.retry(jobId);

  if (result) {
    logger.info({ jobId, newJobId: result.jobId }, 'Retry dispatched');
  } else {
    logger.warn({ jobId }, 'Retry failed - job not found or invalid state');
  }
}

/**
 * Handle approval completion - retry if configured
 */
export async function onApprovalCompleted(
  approvalId: string,
  approved: boolean,
  metadata?: Record<string, unknown>
): Promise<void> {
  if (!approved) return;

  const onApprove = metadata?.onApprove as string;
  const sourceJobId = metadata?.sourceJobId as string;

  if (!sourceJobId) return;

  switch (onApprove) {
    case 'retry_job':
      // Delay to allow resource activation
      scheduleRetry(sourceJobId, 1000, 'resource_created');
      break;

    case 'grant_and_retry':
      // Permission granted, retry
      scheduleRetry(sourceJobId, 500, 'permission_granted');
      break;
  }
}

/**
 * Calculate retry delay with backoff
 */
export function calculateRetryDelay(
  retryCount: number,
  config: RetryConfig = DEFAULT_RETRY_CONFIG
): number {
  return config.delayMs * Math.pow(config.backoffMultiplier, retryCount);
}

/**
 * Check if error is retryable
 */
export function isRetryableError(
  errorCode: string,
  config: RetryConfig = DEFAULT_RETRY_CONFIG
): boolean {
  return config.retryOnErrors.includes(errorCode);
}

// ============================================================================
// EXPORTS
// ============================================================================

export { DEFAULT_RETRY_CONFIG };
