// Template factory for consistent artifact generation

export function skillTemplate(name: string, description: string, capabilities: string[]): {
  'SKILL.md': string;
  'agent-instructions.md': string;
} {
  return {
    'SKILL.md': `# ${name}

${description}

## Capabilities

${capabilities.map(c => `- ${c}`).join('\n')}

## Version

1.0.0

## Requirements

None

## Usage

This skill provides ${capabilities.join(', ')} capabilities.
`,
    'agent-instructions.md': `# Agent Instructions for ${name}

## Overview

You are an agent equipped with the "${name}" skill.

${description}

## Capabilities

${capabilities.map(c => `### ${c}\nImplement ${c} functionality as needed.`).join('\n\n')}

## Guidelines

1. Follow best practices for each capability
2. Validate inputs before processing
3. Return structured JSON responses when applicable
4. Log important operations for debugging
`,
  };
}

export function toolTemplateShell(name: string, description: string): string {
  return `#!/bin/bash
# ${name}
# ${description}
#
# Generated by OCAAS AI Generator
# Version: 1.0.0

set -euo pipefail

usage() {
    echo "Usage: ${name} [options]"
    echo ""
    echo "Options:"
    echo "  -h, --help    Show this help message"
    echo "  -v, --verbose Enable verbose output"
    exit 0
}

main() {
    local verbose=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help) usage ;;
            -v|--verbose) verbose=true; shift ;;
            *) echo "Unknown option: $1"; exit 1 ;;
        esac
    done

    # Main logic here
    echo '{"status": "ok", "tool": "${name}"}'
}

main "$@"
`;
}

export function toolTemplatePython(name: string, description: string): string {
  return `#!/usr/bin/env python3
"""
${name}
${description}

Generated by OCAAS AI Generator
Version: 1.0.0
"""

import argparse
import json
import sys


def main():
    parser = argparse.ArgumentParser(description="${description}")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    args = parser.parse_args()

    result = {
        "status": "ok",
        "tool": "${name}",
    }

    # Main logic here

    print(json.dumps(result))
    return 0


if __name__ == "__main__":
    sys.exit(main())
`;
}

export function agentTemplate(
  name: string,
  description: string,
  type: 'general' | 'specialist' | 'orchestrator',
  capabilities: string[]
): {
  name: string;
  description: string;
  type: 'general' | 'specialist' | 'orchestrator';
  capabilities: string[];
  config: Record<string, unknown>;
} {
  return {
    name,
    description,
    type,
    capabilities,
    config: {
      maxConcurrentTasks: type === 'orchestrator' ? 10 : 3,
      timeout: 300,
      retryOnError: true,
    },
  };
}
